recipe: default.v1
language: en
pipeline:
- name: KeywordIntentClassifier
- name: NLUCommandAdapter
- name: LLMCommandGenerator
  llm:
    model_name: gpt-4
    request_timeout: 7
    temperature: 0.0
    top_p: 0.0
  flow_retrieval:
    embeddings:
      type: openai
      model: text-embedding-3-small
    turns_to_embed: 1
    should_embed_slots: false
    num_flows: 5

policies:
- name: FlowPolicy
- name: EnterpriseSearchPolicy
- name: IntentlessPolicy
